server:
  port: 20000
spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.241.130:8333
  thymeleaf:
    cache: false
  redis:
    host: 192.168.241.130
    port: 6379
  session:
    store-type: redis # 使用redis保存session
    timeout: 30m  # 30分钟过期
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 配置监控
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
gitee:
  client_id:  #填写对应应用id
  client_secret:   #用户密钥
  redirect_uri: http://auth.gulimalls.com/success
