server:
  port: 25000
spring:
  application:
    name: gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.241.130:8333
  redis:
    port: 6379
    host: 192.168.241.130
  session:
    store-type: redis
  rabbitmq:
    host: 119.91.214.57 # host地址
    port: 5672  # 端口
    virtual-host: / # 虚拟主机，默认
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 配置监控
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000