server:
  port: 11000
spring:
  application:
    name: gulimall-ware
  datasource:            # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gulimall-wms?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
  jackson: # 返回前端的格式化时间
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.241.130 # host地址
    port: 5672  # 端口
    virtual-host: / # 虚拟主机，默认
    listener:
      simple:
        acknowledge-mode: manual  # 配置ack为手动应答
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      port: 8719
      dashboard: 192.168.241.130:8333
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 10000
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 配置监控
